### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by dc2000usa** [CSC366/Spring2015-Section-01#3]
When I try to clone the repo, I can get everything except "select*fromjopo" stuff. Its erroring out and not syncing to my local repo. Any ideas on resolving this issue?

**Comment by mslevin** [comment]
Are you trying to clone the repo or get the latest files from github onto your local repo on your machine?

**Comment by dc2000usa** [comment]
I'm trying to clone it in order to get the latest files. I"m using synch in the github gui and it says everything is synched except for that one groups stuff.

**Comment by josxsuen** [comment]
Are you using Windows? select*fromjopo has an asterisk in it, so Windows will not allow it to exist.

**Comment by dc2000usa** [comment]
oo yes i'm using windows... that would explain it...

**Comment by mslevin** [comment]
When you're committing, if you only add the specific files you want to add/change on the repo, it should be fine.

Example: use `git add FinalReport.pdf` instead of `git add -A`

**Comment by dc2000usa** [comment]
git add FinalReport.pdf is literally what I ran :/

**Comment by mslevin** [comment]
If you run `git add FinalsReport.pdf`, and then `git commit`, what does it show that you're changing? Could you post a screenshot?

**Comment by dc2000usa** [comment]
http://puu.sh/iiKhg/20c759f7e6.png

**Comment by dc2000usa** [comment]
Thank you for your help mslevin. A teammate is just going to do it on his computer with ubuntu. It never occurred to me that the issue was the file name for windows. Thank you for your help.
